repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        additional_dependencies: ["types-requests"]
        files: '\.py$'

  - repo: local
    hooks:
      - id: forbid-source-env
        name: forbid `source .env` in shell scripts
        entry: bash -c '! grep -r "source.*\.env" --include="*.sh" .'
        language: system
        files: '\.sh$'
        pass_filenames: false
